### ISSUE TITLE
I am told "The function getScale(int) does not exist" do I miss a library?

### ISSUE THREAD

**Issue by LucasGtte** [lessthanoptimal/BoofProcessing#2]

**Comment by lessthanoptimal** [comment]
need way more information. 

- provide relevant source code. 
- If it's an unmodified example that's failing which one. 
- Version of BoofProcessing. 
- Version of Processing

**Comment by lessthanoptimal** [comment]
I stumbled into the same process myself when updating. It's fixed in the next release
