### ISSUE TITLE
[Feature request] Pattern matching

### ISSUE THREAD

**Issue by Jean-no** [lessthanoptimal/BoofProcessing#3]
It would be great if BoofCV processing library allowed template matching...

**Comment by Jean-no** [comment]
(and by the way, thanks for this excellent tool)

**Comment by lessthanoptimal** [comment]
Thanks for posting this here. When I update this wrapper again I'll run through these issues. Not sure when that will be.

**Comment by lessthanoptimal** [comment]
You now have template matching! Just pushed an update.
