### ISSUE TITLE
is the processing branch up to date?

### ISSUE THREAD

**Issue by TheBricktop** [lessthanoptimal/BoofProcessing#7]
or one should not touch it and jump into pure java for brevity.

**Comment by lessthanoptimal** [comment]
It needs to be updated. Been meaning to add the scene reconstruction code to it. In general, if you want to do work in processing then use this branch. Otherwise stick to the main project. The Processing will always be simplified and not provide all the features available.

**Comment by TheBricktop** [comment]
okay then.
